path: /about
hero:
  subtitle: >-
    Headquartered in Austin, Texas, our team hails from all over the United
    States and Europe, united by their passion for APIs. From skeeball champions
    to rock climbers, tough mudders to restaurateurs, each and every member
    brings their own unique perspectives and experiences to the table. Thinking
    out of the box is our purpose, the weirder the better, and challenging the
    status quo is our culture
  title: About Us
team:
  - image: /images/barnett_headshot.png
    name: Taylor Barnett
    role: Community Engineer
    twitter: '@taylor_atx'
  - image: /images/cassera_headshot.png
    name: Nicholas Cassera
    role: Software Engineer
  - image: /images/chianese_headshot.png
    name: Vincenzo Chianese
    role: Software Engineer
  - image: /images/faust_headshot.png
    name: Scott Faust
    role: Head of Growth
  - image: /images/hilton_headshot.png
    name: William Hilton
    role: Software Engineer
  - image: /images/lott_headshot.png
    name: Chris Lott
    role: Software Engineer
  - image: /images/macleod_headshot.png
    name: Marc MacLeod
    role: Founder & CEO
    twitter: '@marbemac'
  - image: /images/mcdonald_headshot.png
    name: Ross Mcdonald
    role: Sales Engineer
  - image: /images/team/vazha-omanashvili.png
    name: Vazha Omanashvili
    role: Software Engineer
  - image: /images/pytleski_headshot.png
    name: Thomas Pytleski
    role: Software Engineer
  - image: /images/rock_headshot.png
    name: Brian Rock
    role: Director of Engineering
  - image: /images/tharp_headshot.png
    name: Duane Tharp
    role: Sales & Partnerships
  - image: /images/wallach_headshot.png
    name: Robert Wallach
    role: Content & Support
quotes:
  - author: Evin Callahan
    company: Hudya
    image: /images/hudya_logo.png
    quote: >-
      Having all the tools to model, test, and document our API in one place,
      and integrating it nicely along the entire CI/CD workflow process has been
      extremely helpful for us.
    role: Cloud Architect
  - author: Josh Flyer
    company: AppointmentPlus
    image: /images/appointment_plus_logo.png
    quote: >-
      We really enjoy the modeling feature, helping us define our API before
      even writing code. Also, the way the modeling feature inherits models from
      other Projects. Hubs integrates with OAS files, both partials or the
      entire schema, which is rad.
    role: Lead Developer
  - author: Carlos Lozano
    company: GFT Group
    image: /images/gft_group_logo.jpg
    quote: >-
      Stoplight is getting better all the time. Big leap from [Stoplight]
      Classic.
    role: Senior Enterprise Architect
press:
  - description: 'To Help Developers Get A Grip On APIs, Stoplight Raises $3.25M'
    image: /images/logo_crunchbase.png
    publication: crunchbase news
    date: October, 2018
    href: https://news.crunchbase.com/news/to-help-developers-get-a-grip-on-apis-stoplight-raises-3-25m
  - description: >-
      Software startup raises more than $3M in round led by former Austin
      Ventures bigwig
    image: /images/logo_austin_bj.png
    publication: Austin Business Journal
    date: October, 2018
    href: https://www.bizjournals.com/austin/news/2018/10/03/software-startup-raises-more-than-3m-in-round-led.html
  - description: >-
      Stoplight Lands $3.25M of Seed Funding to Lead Evolution of Enterprise API
      Lifecycle Management
    image: /images/logo_venturebeat.png
    publication: VentureBeat
    date: October, 2018
    href: https://venturebeat.com/2018/10/03/stoplight-lands-3-25m-of-seed-funding-to-lead-evolution-of-enterprise-api-lifecycle-management
investors:
  - image: /images/bill-wood-logo_trans.png
    name: Bill Wood Ventures
  - image: /images/logo_next_gen_ventures.png
    name: NextGen Venture Partners
  - image: /images/logo_nextcoast.png
    name: Next Coast Ventures
  - image: /images/logo_techstars.png
    name: Techstars
  - image: /images/logo_capitalfactory.png
    name: Capital Factory
  - image: /images/logo_socialstarts.png
    name: Social Starts
actionBar:
  buttons:
    - color: accent
      href: 'https://angel.co/stoplight/jobs'
      title: Learn More
  enabled: true
  text: Want to join the team? We're hiring!
meta:
  favicon: /images/mark_light_bg.png
  title: Learn About Us | Stoplight
  twitter:
    title: Learn About Us | Stoplight
    username: '@stoplightio'
