hero:
  bgColor: black
  cards:
    - bgColor: blue
      href: /design
      icon:
        name: paint-brush
        style: solid
      subtitle: Use our visual designer to manage OpenAPI (Swagger) 10x faster
      title: Design
    - bgColor: green
      href: /documentation
      icon:
        name: book
        style: solid
      subtitle: 'Increase customer adoption with beautiful, functional documentation'
      title: Documentation
    - bgColor: orange
      href: /testing
      icon:
        name: flask
        style: solid
      subtitle: 'Leverage OpenAPI to test, automate, and debug web APIs'
      title: Testing
    - bgColor: grey-darkest
      href: /mocking
      icon:
        name: server
        style: solid
      subtitle: 'Parallelize development with one click mock servers, powered by Prism'
      title: Mocking
  cta:
    href: 'https://next.stoplight.io/'
    name: Get Started Now
  particles: true
  skew: rounded
  subtitle: >-
    Stoplight leverages your OpenAPI files to drive the entire API development
    process
  title: 'Best in class API Design, Docs, Mocking, and Testing'
product:
  cta:
    href: 'https://next.stoplight.io/'
    name: Get Started Now
  description: >-
    Create OpenAPI Specifications (formerly known as Swagger) 10x faster with no
    specialized knowledge required. Combine OpenAPI documents with Markdown to
    create beautiful documentation for internal and external stakeholders.
    Instantly turn any OpenAPI document into a mock server. Leverage contract
    testing to ensure that your Single Source of Truth - OpenAPI Specification -
    accurately describe your APIs.
  image: /images/home-hero.png
  title: The Complete OpenAPI Specification Toolkit
customers:
  - /images/ea.png
  - /images/logo_arkea_transparent.png
  - /images/chargify-new-logo.png
  - /images/deutsche_bank.png
  - /images/customers/quicken.png
  - /images/logo-sendgrid.png
  - /images/shopgate.png
  - /images/spotify.png
  - /images/tivo.png
  - /images/logo_zendesk.png
testimonials:
  - author: Kin Lane
    image: /images/testimonials/kin_lane.jpeg
    quote: >-
      I feel like Stoplight has the potential to shift the landscape pretty
      significantly, something I haven't seen any API service provider do in a
      while.
    role: API Evangelist
  - author: 'Carlos Lozano '
    image: /images/carlos_testimonial.jpeg
    quote: >-
      When it comes to specification markup and documentation, the order of
      magnitude has gone from days to hours.
    role: 'Senior Enterprise Architect, GFT Group'
  - author: John Vajda
    image: /images/testimonials/john_vajda.jpeg
    quote: >-
      Stoplight has been a serious game changer for JumpCloudâ€™s API development!
      We love all the rich design, documentation and testing features, which has
      enabled us to design awesome APIs for our customers.
    role: 'Product Manager, JumpCloud'
  - author: Gil Barbara
    image: /images/testimonials/gil.jpeg
    quote: >-
      Stoplight provides a centralized, testable and reliable source for our
      APIs.
    role: 'Frontend Engineer, AMARO'
actionBar:
  enabled: true
